### ISSUE TITLE
Generowanie sprzecznych obostrzeń

### ISSUE THREAD

**Issue by Monobastian** [808-Squad/koronawirus.lol#1]
Panie, to zbyt prawdziwe jest, do tego stopnia że zbyt sprzeczne aby ludzie w to uwierzyli. Generowane obostrzenia czasem się wykluczają. Przykładowo zakaz chodzenia do restauracji całkowicie i zaraz pod nim pozwolenie na chodzenie do restauracji takie kodzenie się nie godzi! Nawet generatorowi zrobionemu dla beki nie przystoi takie mieszanie faktów.

**Comment by krethh** [comment]
@Monobastian nie narzekaj, bo znajdziesz się w liście osób dla których otwarte są hotele.

A tak serio, to to jest medium quality shitpost, nie chce nam się tego bardziej poprawiać.
