### ISSUE TITLE
Translation support when?

### ISSUE THREAD

**Issue by krzysztof-sikorski** [808-Squad/koronawirus.lol#4]
This is brilliant lolcontent, but it is hard to spam foreign friends with it if they cannot read it and thus appreciate it...

**Comment by krethh** [comment]
We are thinking about it. We might release an English-speaking version over the weekend

**Comment by marco-manza** [comment]
I'd love to share it with my friends. If you want help with Italian, let me know ;)

**Comment by krethh** [comment]
@marco-manza Support for internationalization has been added - if you want to translate the content into Italian you are welcome  to do so - see instructions in README.

**Comment by krzysztof-sikorski** [comment]
Translation strings for English are actually in Polish - is this intended?

**Comment by krethh** [comment]
This is a placeholder for now.

**Comment by dzierzanowski** [comment]
It was a **_lenghty weekend,_** but a reasonably funny version in English is now live.
