### ISSUE TITLE
Przycisk Messenger nie działa

### ISSUE THREAD

**Issue by JChoptiany** [808-Squad/koronawirus.lol#5]
Po najechaniu na przycisk kursor nie zmienia się na pointer, a kliknięcie dodaje jedynie czarne krawędzie. Nie otwiera się żadne okno.

**Comment by dzierzanowski** [comment]
Share'owanie przez Messengera z komputera nie działa zbyt dobrze (w zasadzie w ogóle), więc przycisk jest wyłączony. Pewnie go w ogóle ukryjemy na większych ekranach.
