### ISSUE TITLE
Chyba wam hosting coś zablokował...

### ISSUE THREAD

**Issue by ghost** [808-Squad/koronawirus.lol#6]
Strony nie ma. Jak się domyślam miała tak dużą popluarność, że hosting ją zablokował :(

**Comment by krethh** [comment]
Nope, zwykłe testowanie na prodzie. Już wróciła.

**Comment by dzierzanowski** [comment]
Ten projekt prowadzimy w oparciu o Production Driven Development.

**Comment by krethh** [comment]
Jak w każdym poważnym projekcie, należy opublikować _post mortem_ buga.
**Opis zdarzenia:**  strona nie działała przez jakieś 17 minut.
**Czego nas to nauczyło:** patrz gdzie klikasz.
